# Generated by Django 3.2.5 on 2022-01-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='cy_goods_brand',
        ),
        migrations.AlterModelTable(
            name='goods',
            table='cy_goods_spu',
        ),
        migrations.AlterModelTable(
            name='sku',
            table='cy_goods_sku',
        ),
        migrations.AlterModelTable(
            name='skuimage',
            table='cy_goods_sku_image',
        ),
    ]
